// Re-export shared types so existing components that import from
// "@/lib/chat-schema" keep working without a zod dependency in the browser.
export type {
	ChatMessage,
	ChatMessageMeta,
	ChatMessageRole,
	ChatSessionConfig,
	ChatSessionStatus,
	ChatSummary,
	SessionRecord,
	AgentChunkEvent,
	ToolApprovalRequestItem,
	ProcessContext,
	ChatDonePayload,
	ToolCallStartPayload,
	ToolCallUpdatePayload,
	ToolCallEndPayload,
	ChatUsagePayload,
	EngineState,
	EngineStatusPayload,
	ProviderProtocol,
	ApiProfilePayload,
	ModelSettingsPayload,
	ConnectionTestResult,
	FileDiffEntryPayload,
	ToolNodePayload,
	AppInfoPayload,
	SessionListItemPayload,
	ProjectListItemPayload,
} from "@shared/types";
